/*
 * Spotify Web API
 *
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spotify;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AudioAnalysisObject {
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<spotify::AudioAnalysisObjectMeta>>,
    #[serde(rename = "track", skip_serializing_if = "Option::is_none")]
    pub track: Option<Box<spotify::AudioAnalysisObjectTrack>>,
    /// The time intervals of the bars throughout the track. A bar (or measure) is a segment of time defined as a given number of beats.
    #[serde(rename = "bars", skip_serializing_if = "Option::is_none")]
    pub bars: Option<Vec<spotify::TimeIntervalObject>>,
    /// The time intervals of beats throughout the track. A beat is the basic time unit of a piece of music; for example, each tick of a metronome. Beats are typically multiples of tatums.
    #[serde(rename = "beats", skip_serializing_if = "Option::is_none")]
    pub beats: Option<Vec<spotify::TimeIntervalObject>>,
    /// Sections are defined by large variations in rhythm or timbre, e.g. chorus, verse, bridge, guitar solo, etc. Each section contains its own descriptions of tempo, key, mode, time_signature, and loudness.
    #[serde(rename = "sections", skip_serializing_if = "Option::is_none")]
    pub sections: Option<Vec<spotify::SectionObject>>,
    /// Each segment contains a roughly conisistent sound throughout its duration.
    #[serde(rename = "segments", skip_serializing_if = "Option::is_none")]
    pub segments: Option<Vec<spotify::SegmentObject>>,
    /// A tatum represents the lowest regular pulse train that a listener intuitively infers from the timing of perceived musical events (segments).
    #[serde(rename = "tatums", skip_serializing_if = "Option::is_none")]
    pub tatums: Option<Vec<spotify::TimeIntervalObject>>,
}

impl AudioAnalysisObject {
    pub fn new() -> AudioAnalysisObject {
        AudioAnalysisObject {
            meta: None,
            track: None,
            bars: None,
            beats: None,
            sections: None,
            segments: None,
            tatums: None,
        }
    }
}

