/*
 * Spotify Web API
 *
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spotify;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaylistTrackObject {
    /// The date and time the track or episode was added. _**Note**: some very old playlists may return `null` in this field._ 
    #[serde(rename = "added_at", skip_serializing_if = "Option::is_none")]
    pub added_at: Option<String>,
    /// The Spotify user who added the track or episode. _**Note**: some very old playlists may return `null` in this field._ 
    #[serde(rename = "added_by", skip_serializing_if = "Option::is_none")]
    pub added_by: Option<Box<spotify::PlaylistUserObject>>,
    /// Whether this track or episode is a [local file](/documentation/web-api/concepts/playlists/#local-files) or not. 
    #[serde(rename = "is_local", skip_serializing_if = "Option::is_none")]
    pub is_local: Option<bool>,
    #[serde(rename = "track", skip_serializing_if = "Option::is_none")]
    pub track: Option<Box<spotify::PlaylistTrackObjectTrack>>,
}

impl PlaylistTrackObject {
    pub fn new() -> PlaylistTrackObject {
        PlaylistTrackObject {
            added_at: None,
            added_by: None,
            is_local: None,
            track: None,
        }
    }
}

