/*
 * Spotify Web API
 *
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spotify;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferAUsersPlaybackRequest {
    /// A JSON array containing the ID of the device on which playback should be started/transferred.<br/>For example:`{device_ids:[\"74ASZWbe4lXaubB36ztrGX\"]}`<br/>_**Note**: Although an array is accepted, only a single device_id is currently supported. Supplying more than one will return `400 Bad Request`_ 
    #[serde(rename = "device_ids")]
    pub device_ids: Vec<String>,
    /// **true**: ensure playback happens on new device.<br/>**false** or not provided: keep the current playback state. 
    #[serde(rename = "play", skip_serializing_if = "Option::is_none")]
    pub play: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl TransferAUsersPlaybackRequest {
    pub fn new(device_ids: Vec<String>) -> TransferAUsersPlaybackRequest {
        TransferAUsersPlaybackRequest {
            device_ids,
            play: None,
        }
    }
}

