/*
 * Spotify Web API
 *
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spotify;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageObject {
    /// The source URL of the image. 
    #[serde(rename = "url")]
    pub url: String,
    /// The image height in pixels. 
    #[serde(rename = "height", deserialize_with = "Option::deserialize")]
    pub height: Option<i32>,
    /// The image width in pixels. 
    #[serde(rename = "width", deserialize_with = "Option::deserialize")]
    pub width: Option<i32>,
}

impl ImageObject {
    pub fn new(url: String, height: Option<i32>, width: Option<i32>) -> ImageObject {
        ImageObject {
            url,
            height,
            width,
        }
    }
}

