/*
 * Spotify Web API
 *
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::spotify;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecommendationsObject {
    /// An array of recommendation seed objects. 
    #[serde(rename = "seeds")]
    pub seeds: Vec<spotify::RecommendationSeedObject>,
    /// An array of track object (simplified) ordered according to the parameters supplied. 
    #[serde(rename = "tracks")]
    pub tracks: Vec<spotify::TrackObject>,
}

impl RecommendationsObject {
    pub fn new(seeds: Vec<spotify::RecommendationSeedObject>, tracks: Vec<spotify::TrackObject>) -> RecommendationsObject {
        RecommendationsObject {
            seeds,
            tracks,
        }
    }
}

