name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu,armv7-unknown-linux-musleabihf]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        env:
          MELODY_PLUS_CLIENT_ID: ${{ secrets.MELODY_PLUS_CLIENT_ID }}
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Upload Binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: target/${{ matrix.target }}/release/melody_plus*