name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Linux and Windows Cross Compilers
      run: sudo apt-get install --yes --no-install-recommends musl-tools gcc-mingw-w64-x86-64-win32
    - name: Install Rustup targets
      run: rustup target add x86_64-pc-windows-gnu
    - uses: actions/checkout@v3
    - name: Build
      env:
        MELODY_PLUS_CLIENT_ID: ${{ secrets.MELODY_PLUS_CLIENT_ID }}
      run: cargo build --verbose --target=x86_64-pc-windows-gnu
    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: target
