name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
    - uses: actions/checkout@v3
    - name: Build
      env:
        MELODY_PLUS_CLIENT_ID: ${{ secrets.MELODY_PLUS_CLIENT_ID }}
      run: cargo build --verbose --target=x86_64-pc-windows-msvc
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "target/x86_64-pc-windows-msvc/release/*.exe"
        prerelease: true
